apiVersion: v2
name: stat-receiver
type: application
description: A Helm chart for Kubernetes to deploy Stat Receiver

version: 2.46.0
appVersion: 1.15.21

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
