apiVersion: v2
name: tilegen-api
description: API for generating vector tiles from user data

type: application

version: 2.49.0
appVersion: 1.1.8

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
