{{- define "generic-chart.httpRoute.tpl" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "generic-chart.fullname" . }}
spec:
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: canary
      namespace: istio-gateways
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: stable
      namespace: istio-gateways
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{  include "generic-chart.fullname" . }}
          port: {{ (.Values.service).port | default 80 | int }}
          weight: 1
{{- end }}{{/* define */}}
