{{- if .Values.dispatcher.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "keys.cleaner.name" . }}
  labels:
    {{- include "keys.cleaner.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  schedule: "{{ .Values.dispatcher.cleaner.cron.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.dispatcher.cleaner.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.dispatcher.cleaner.cron.failedJobsHistoryLimit }}
  suspend: {{ .Values.dispatcher.cleaner.cron.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "keys.cleaner.name" . }}
          labels:
            {{- include "keys.cleaner.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          {{- with include "keys.psql.initTLS" . }}
          initContainers:
          {{- . | nindent 12 }}
          {{- end }}
          containers:
            - name: clean
              image: {{ required "A valid .Values.dgctlDockerRegistry entry required" .Values.dgctlDockerRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              command: [ "keysctl", "clear" ]
              args: [ "audit_events" ]
              resources:
                {{- toYaml .Values.dispatcher.cleaner.resources | nindent 16 }}
              env:
                {{- include "keys.env.db.deploys" . | nindent 16 }}
                {{- include "keys.env.cleaner" . | nindent 16 }}
                {{- if .Values.customCAs.bundle }}
                {{- include "keys.env.custom.ca.path" . | nindent 16 }}
                {{- end }}
              volumeMounts:
              {{- if .Values.customCAs.bundle }}
              {{- include "keys.custom.ca.volumeMounts" . | nindent 16 }}
              {{- end }}
              {{- include "keys.psql.volumeMount" . | nindent 16 }}
          volumes:
          {{- if .Values.customCAs.bundle }}
          {{- include "keys.custom.ca.jobs.volumes" . | nindent 12 }}
          {{- end }}
          {{- include "keys.psql.volume" . | nindent 12 }}
          {{- with .Values.dispatcher.cleaner.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
