{{- with .Values.serviceApi.hpa }}
{{- if .enabled }}
apiVersion: {{ include "capabilities.hpa.apiVersion" $ }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "service.api.name" $ }}
  labels:
    {{- include "service.api.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.api.name" $ }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  behavior:
    scaleUp:
        stabilizationWindowSeconds: {{ .scaleUpStabilizationWindowSeconds }}
    scaleDown:
        stabilizationWindowSeconds: {{ .scaleDownStabilizationWindowSeconds }}
  metrics:
  {{- with .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
