apiVersion: v2
name: mapgl-js-api
description: Basic WebGL map chart template for 2GIS On-Premise

type: application

version: 2.48.0
appVersion: 1.69.1

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
