{{- if .Values.head.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "search-api.fullname" . }}-head
  labels:
    {{- include "search-api.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "search-api.fullname" . }}-head
  updatePolicy:
    updateMode: {{ ternary "On" "Off" .Values.head.vpa.updateMode | quote }}
{{- end }}
