{{- if .Values.proxy.locationDG }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-chart.name" . }}-secret
  labels:
    {{- include "generic-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key.conf: |
    proxy_set_header   X-API-Key {{ required "A valid .Values.proxy.licenseKey required" .Values.proxy.licenseKey }};
{{- end }}
