apiVersion: v2
name: platform
type: application
description: A Helm chart for Kubernetes to deploy Platform

version: 2.49.0
appVersion: 1.24.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
