{{- if empty .Values.indexerServices.externalFilesStorageUrl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-api.fullname" . }}-controller
  labels:
    {{- include "search-api.labels" . | nindent 4 }}
    search/part: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "search-api.selectorLabels" . | nindent 6 }}
    {{- with .Values.controller.matchLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}{{- /* .Values.controller.matchLabels */}}
      search/part: controller
  template:
    metadata:
      annotations:
      {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.podAnnotations */}}
        checksum/config: {{ include (print $.Template.BasePath "/common/configmap.yaml") . | sha256sum }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.controller.ports.http | quote }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "search-api.labels" . | nindent 8 }}
        search/part: controller
      {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.podLabels */}}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.imagePullSecrets */}}
      serviceAccountName: {{ include "search-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          env:
            - name: GINMODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: GINMODE
            - name: s3AccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3AccessKey
            - name: s3SecretKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3SecretKey
            - name: s3Host
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3Host
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          ports:
            - name: http
              containerPort: {{ .Values.controller.ports.http }}
          volumeMounts:
            - name: controller-config
              mountPath: /app/config.yaml
              subPath: controller.yaml
            - name: controller-data
              mountPath: /tmp
          {{- if .Values.customCAs.bundle }}
            {{- include "search-api.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          {{- if .Values.controller.livenessProbe.enabled }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.controller.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{ end -}}{{- /* .Values.controller.livenessProbe.enabled */}}
          {{- if .Values.controller.readinessProbe.enabled }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.controller.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{ end -}}{{- /* .Values.controller.readinessProbe.enabled */}}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.nodeSelector */}}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.affinity */}}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.controller.tolerations */}}
      volumes:
        - name: controller-config
          configMap:
            name: {{ include "search-api.fullname" . }}
        {{- if .Values.controller.data.persistent.enabled }}
        - name: controller-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: {{ .Values.controller.data.storageClassName | quote }}
                volumeMode: Filesystem
                resources:
                  {{- .Values.controller.data.resources | toYaml | nindent 18 }}
        {{ else }}
        - name: controller-data
          emptyDir:
            sizeLimit: {{ .Values.controller.data.resources.requests.storage }}
        {{ end }}{{- /* .Values.controller.data.persistent.enabled */}}
        {{- if .Values.customCAs.bundle }}
        {{- include "search-api.custom.ca.deploys.volumes" . | nindent 8 }}
        {{- end }}{{- /* .Values.customCAs.bundle */}}
  {{- end }}{{- /* .Values.indexerServices.externalFilesStorageUrl */}}
