{{- if and (.Values.indexer.vpa.enabled) (empty .Values.indexerServices.externalFilesStorageUrl) }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "search-api-v8.fullname" . }}-indexer
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "search-api-v8.fullname" . }}-indexer
  updatePolicy:
    updateMode: {{ ternary "On" "Off" .Values.indexer.vpa.updateMode | quote }}
{{- end }}
