apiVersion: v2
name: pro-api
description: Geo API for getting geo data

type: application

version: 2.2.0
appVersion: 2.51.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
