apiVersion: v2
name: traffic-proxy
description: A Helm chart for Kubernetes to deploy Proxy for traffic jams

type: application

version: 2.46.0
appVersion: 1.25.5

dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
