apiVersion: v2
name: navi-async-matrix
description: Service implements asynchronous API over Distance Matrix

type: application

version: 2.47.1
appVersion: 1.19.3

dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart
maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
