apiVersion: v2
name: navi-router
description: Navi router Helm chart for Kubernetes
type: application
keywords:
- navi
- router
version: 2.46.0
appVersion: 6.35.0.3
dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart
maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
