apiVersion: v2
name: navi-attractor
description: Attractor Helm chart
type: application
keywords:
- navi
- attractor
version: 2.44.0
appVersion: 7.42.0.3
dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart
maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
