apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citylens.routes.api.name" . }}-api-key-secret
type: Opaque
data:
  dataScienceApiKey: {{ required "Valid .Values.routes.endpointInternalApiKey.dataScience required!" .Values.routes.endpointInternalApiKey.dataScience | b64enc }}
  companiesApiKey: {{ required "Valid .Values.routes.endpointInternalApiKey.companies required!" .Values.routes.endpointInternalApiKey.companies | b64enc }}
