apiVersion: v2
name: navi-vrp-solver
description: Navi VRP Solver helm chart for Kubernetes
type: application
keywords:
- navi
- vrp
- tsp
- solver
version: 2.46.0
appVersion: 1.13.1
dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart
maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
