{{- if .Values.geodetector.enabled }}
{{- if .Values.geodetector.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "search-api-v8.fullname" . }}-geodetector
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "search-api-v8.fullname" . }}-geodetector
  updatePolicy:
    updateMode: {{ ternary "On" "Off" .Values.geodetector.vpa.updateMode | quote }}
{{- end }}{{- /* .Values.geodetector.vpa.enabled */}}
{{- end }}{{- /* .Values.geodetector.enabled */}}
