{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-api-v8.fullname" . }}-worker
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.worker.port }}
      targetPort: {{ .Values.worker.ports.grpc }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "search-api-v8.selectorLabels" . | nindent 4 }}
    search/part: worker
{{- end }}{{- /* .Values.worker.enabled */}}
