{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "search-api-v8.serviceAccountName" . }}
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* .Values.serviceAccount.annotations */}}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}{{- /* .Values.serviceAccount.create */}}
