apiVersion: v2
name: catalog-api
type: application
description: A Helm chart for Kubernetes to deploy Catalog APIs

version: 2.49.0
appVersion: 3.665.1

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
