apiVersion: v2
name: tiles-api
description: Tiles API for getting cartographic data

type: application

version: 2.49.0
appVersion: 4.81.3

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
