{{- if $.Values.cassandra.tls.deploySecret }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "tiles.fullname" . }}-tls
  labels:
    {{- include "tiles.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"

type: Opaque
data:
{{- if $.Values.cassandra.tls.cert }}
  client.crt: {{ $.Values.cassandra.tls.cert | b64enc | quote }}
{{- end }}
{{- if $.Values.cassandra.tls.key }}
  client.key: {{ $.Values.cassandra.tls.key | b64enc | quote }}
{{- end }}
{{- if $.Values.cassandra.tls.ca }}
  ca.crt: {{ $.Values.cassandra.tls.ca | b64enc | quote }}
{{- end }}
{{- end }}
