{{- if empty .Values.indexerServices.externalFilesStorageUrl }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-api.fullname" . }}-indexer
  labels:
    {{- include "search-api.labels" . | nindent 4 }}
    search/part: indexer
spec:
  {{- if not .Values.indexer.hpa.enabled }}
  replicas: {{ .Values.indexer.replicaCount }}
  {{- end }}{{- /* not .Values.indexer.hpa.enabled */}}
  selector:
    matchLabels:
      {{- include "search-api.selectorLabels" . | nindent 6 }}
    {{- with .Values.indexer.matchLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}{{- /* .Values.indexer.matchLabels */}}
      search/part: indexer
  template:
    metadata:
      annotations:
      {{- with .Values.indexer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.podAnnotations */}}
        checksum/config: {{ include (print $.Template.BasePath "/common/configmap.yaml") . | sha256sum }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.indexer.ports.http | quote }}
        prometheus.io/scrape: "true"
      labels:
        {{- include "search-api.labels" . | nindent 8 }}
        search/part: indexer
      {{- with .Values.indexer.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.podLabels */}}
    spec:
      {{- with .Values.indexer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.imagePullSecrets */}}
      serviceAccountName: {{ include "search-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.indexer.podSecurityContext | nindent 8 }}
      containers:
        - name: indexer
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}
          env:
            - name: GINMODE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: GINMODE
            - name: s3AccessKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3AccessKey
            - name: s3SecretKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3SecretKey
            - name: s3Host
              valueFrom:
                secretKeyRef:
                  name: {{ include "search-api.fullname" . }}
                  key: s3Host
            {{- if .Values.customCAs.bundle }}
            {{- include "search-api.env.custom.ca.path" . | nindent 12 }}
            {{- end }}{{- /* .Values.customCAs.bundle */}}
          ports:
            - name: http
              containerPort: {{ .Values.indexer.ports.http }}
          volumeMounts:
            - name: indexer-config
              mountPath: /app/config.yaml
              subPath: indexer.yaml
          {{- if .Values.customCAs.bundle }}
            {{- include "search-api.custom.ca.volumeMounts" . | nindent 12 }}
          {{- end }}{{- /* .Values.customCAs.bundle */}}
          {{- if .Values.indexer.livenessProbe.enabled }}
          livenessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.indexer.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{ end -}}{{- /* .Values.indexer.livenessProbe.enabled */}}
          {{- if .Values.indexer.readinessProbe.enabled }}
          readinessProbe:
            {{- include "common.tplvalues.render" (dict "value" (omit .Values.indexer.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{ end -}}{{- /* .Values.indexer.readinessProbe.enabled */}}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.nodeSelector */}}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.affinity */}}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* .Values.indexer.tolerations */}}
      volumes:
        - name: indexer-config
          configMap:
            name: {{ include "search-api.fullname" . }}
        {{- if .Values.customCAs.bundle }}
        {{- include "search-api.custom.ca.deploys.volumes" . | nindent 8 }}
        {{- end }}{{- /* .Values.customCAs.bundle */}}
{{- end }}{{- /* empty .Values.indexerServices.externalFilesStorageUrl */}}
