{{- if .Values.onpremise }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-api.fullname" . }}-data-adapter
  labels:
    {{- include "search-api.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.dataAdapter.port }}
      targetPort: {{ .Values.dataAdapter.ports.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "search-api.selectorLabels" . | nindent 4 }}
    search/part: data-adapter
{{- end }}
