apiVersion: v2
name: stat-api
type: application
description: A Helm chart for Kubernetes to deploy Stat service

version: 2.50.0
appVersion: 0.2.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
