apiVersion: v2
name: pro-ui
type: application
description: A Helm chart for Kubernetes to deploy 2GIS Pro UI service

version: 2.2.0
appVersion: 4.42.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
