{{- if .Values.pagerenderer.settings.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pro-api.pagerenderer-name" . }}
  {{- with .Values.pagerenderer.pod.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "pro-api.rendererLabels" . | nindent 4 }}
  {{- with .Values.pagerenderer.pod.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.pagerenderer.pod.replicaCount }}
  revisionHistoryLimit: {{ .Values.pagerenderer.pod.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "pro-api.rendererSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.pagerenderer.pod.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pro-api.rendererLabels" . | nindent 8 }}
      {{- with .Values.pagerenderer.pod.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.pagerenderer.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pagerenderer.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pagerenderer.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pagerenderer.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.pagerenderer.pod.priorityClassName }}
      priorityClassName: {{ .Values.pagerenderer.pod.priorityClassName }}
      {{- end }}
      {{- with .Values.pagerenderer.pod.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.pagerenderer.pod.terminationGracePeriodSeconds }}
      containers:
        - name: {{ include "pro-api.pagerenderer-name" . }}
          image: {{ required "A valid .Values.dgctlDockerRegistry entry required" $.Values.dgctlDockerRegistry }}/{{ .Values.pagerenderer.image.repository }}:{{ .Values.pagerenderer.image.tag }}
          imagePullPolicy: {{ .Values.pagerenderer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pagerenderer.settings.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.pagerenderer.settings.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 20
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.pagerenderer.pod.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          env:
            - name: ENV
              value: {{ .Values.pagerenderer.settings.env | quote }}
            - name: Common__HttpPort
              value: {{ .Values.pagerenderer.settings.httpPort | quote }}
            - name: Common__GrpcPort
              value: {{ .Values.pagerenderer.settings.grpcPort | quote }}
            - name: Common__Logging__Format
              value: {{ .Values.pagerenderer.settings.logging.format | quote }}
            - name: Common__Logging__Targets
              value: {{ .Values.pagerenderer.settings.logging.targets | quote }}
            - name: ApiKey
              valueFrom:
                secretKeyRef:
                  key: pagerendererApiKey
                  name: {{ include "pro-api.name" . }}-secret
{{- end }}
