{{- if .Values.pagerenderer.settings.enabled }}
{{- with .Values.pagerenderer.pdb }}
{{- if .enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pro-api.pagerenderer-name" $ }}
  labels:
    {{- include "pro-api.rendererLabels" $ | nindent 4 }}
spec:
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pro-api.rendererSelectorLabels" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
