{{- if .Values.pagerenderer.settings.enabled }}
{{- if .Values.pagerenderer.vpa.enabled }}
---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "pro-api.pagerenderer-name" . }}
  labels:
    {{- include "pro-api.rendererLabels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pro-api.pagerenderer-name" . }}
  updatePolicy:
    updateMode: {{ .Values.pagerenderer.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        controlledValues: RequestsOnly
        mode: Auto
        {{- with .Values.pagerenderer.vpa.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.pagerenderer.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
{{- end }}
