{{- if empty .Values.indexerServices.externalFilesStorageUrl }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-api-v8.fullname" . }}-files-storage
  labels:
    {{- include "search-api-v8.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.filesStorage.port }}
      targetPort: {{ .Values.filesStorage.ports.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "search-api-v8.selectorLabels" . | nindent 4 }}
    search/part: files-storage
{{- end }}
