apiVersion: v2
name: navi-vrp-task-manager
description: Navi VRP Task Manager helm chart for Kubernetes
type: application
keywords:
- navi
- vrp
- tsp
- task-manager
version: 2.48.0
appVersion: 1.13.1
dependencies:
- name: generic-chart
  version: '*'
  repository: file://../generic-chart
maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
