apiVersion: v2
name: styles-api
type: application
description: A Helm chart for Kubernetes to deploy API Styles service

version: 2.47.1
appVersion: 0.42.0

maintainers:
- name: 2gis
  url: https://github.com/2gis
  email: on-premise@2gis.com
